name: 'build-test'
on:
  pull_request:

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  test:
    name: run test ${{ matrix.os }} sdkversion ${{ matrix.sdk }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: remove android sdk from ubuntu-latest
        shell: bash
        run: |
          echo 'ANDROID_HOME=' >> $GITHUB_ENV
          echo 'ANDROID_SDK_ROOT=' >> $GITHUB_ENV
          rm -rf ~/android

      - uses: ./.github/composite/summary-test

      - run: |
          ./sample-android-project/gradlew -p sample-android-project assembleDebug --stacktrace